Add CSS rules for bigger screen sizes
gnuion/microverse_first_capstone_project pull request #2
Opened 2022-07-26 13:24 UTC by gnuion

With this pull request I:
- Add CSS rules for bigger screen sizes
- Update readme
- Change some content
- Add favicon
- Add link to [presentation video](https://www.loom.com/share/73844865f82346daa8bc28d535961f70)

2022-07-26 19:18 UTC, danmainah requested changes
Hi @gnuion, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️  Good design


# Required Changes ♻️

- [ ] Kindly ensure to use the GitHub flow correctly, master or main should be your base branch.

- [ ] Kindly ensure to capture clearly what your project is about, you didn't describe for instance `an institution's website informing potential students of what the institution offers`, 

- [ ] Kindly ensure the footer section for the about page desktop view has a dark background as it's in the design:

Design    Given      |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/181087599-4dd4e94e-d6d6-4d6b-b453-5e2bbe33f42f.png) | ![image](https://user-images.githubusercontent.com/61408860/181087656-bfa80786-88de-4dc8-85b8-4c2e171a47e8.png)

- [ ] Kindly ensure to add background images as in the design, currently both your pages don't have background images.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-26 19:18 UTC, danmainah commented on about.html
> +          <h1>Studeio Development Logo</h1>
- [ ] Kindly ensure you have only one h1 element on your page, the `<h1>` tag is used to semantically specify the main header of the page, and helper search engines and web crawlers easily understand the main subject of your page.

2022-07-26 19:18 UTC, danmainah commented on about.html
>              <img src="./public/images/event1.jpg" alt="" />
- [ ] Kindly add image `alt` attributes, they shouldn't be empty and should be used to make users understand what the image represents in case the image doesn't display.

2022-07-26 19:18 UTC, danmainah commented on index.html
>                    <img src="./public/images/program_icon_02.png" alt="" />
- [ ] Kindly add image alt attributes, they shouldn't be empty and should be used to make users understand what the image represents in case the image doesn't display.

2022-07-26 19:18 UTC, danmainah commented on index.html
>          </h1>
- [ ]  Kindly add image alt attributes, they shouldn't be empty and should be used to make users understand what the image represents in case the image doesn't display.

2022-07-26 19:25 UTC, gnuion commented on about.html
> +          <h1>Studeio Development Logo</h1>
Okay, you have a point here.

2022-07-26 19:26 UTC, gnuion commented on index.html
>          </h1>
Yes, I will do it.

2022-07-26 19:27 UTC, gnuion commented on index.html
Please notice other breakpoints. This shows me that you didn't watch my video at all!

2022-07-26 19:31 UTC, gnuion commented on index.html
>                    <img src="./public/images/program_icon_02.png" alt="" />
Okay, you also have a point here.

2022-07-26 19:32 UTC, gnuion commented on about.html
>              <img src="./public/images/event1.jpg" alt="" />
Okay, you have a point here.

2022-07-26 19:40 UTC, gnuion commented on index.html
Please also note that the designer is not being consistent with their design.

Figma Design  |  Also Figma Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/16549839/181097540-f031e809-e53e-4d0a-a387-d5801e616dd9.png) |  ![image](https://user-images.githubusercontent.com/16549839/181097435-7b769618-fc14-41e6-8b43-11676bd7fdb9.png)

2022-07-26 19:52 UTC, gnuion commented on index.html
Okay, but for very small screen sizes it won't work.

2022-07-26 20:48 UTC, nicupop729 reviewed
Hello @gnuion 👋,

_This is an additional review as a result of the second opinion request._

Very nice project you have here! :confetti_ball: Congratulations! :clap:

Please implement the following requests from the previous reviewer:

- [ ]  Kindly ensure to use the GitHub flow correctly, master or main should be your base branch.
- [ ]  Kindly ensure the footer section for the about page desktop view has a dark background as it's in the design;
- [ ]  Kindly ensure to add background images as in the design, currently both your pages don't have background images.
- [ ] Kindly ensure to include the top short bar section with social media links, logout, and language links as in the design


Being in this position, please understand that Microverse tries to replicate as much as possible the workflow from an environment of developers: 
- a designer creates the design;
- a team of developers creates the app following the design (where they assume that if the design seems to be inconsistent, it was intended; they can always double-check, of course, but in this case, the inconsistencies spotted very well by you, were intended);
- and there are the team leaders who are reviewing and checking the code;

As this flow was intended, please try to get the advice from the reviewers as they only want to help

Keep rocking 🚀!

2022-07-26 20:48 UTC, nicupop729 commented on index.html
- [ ] In order to respect the design, please make sure to restyle this part of the project. :+1:

2022-07-26 20:48 UTC, nicupop729 commented on index.html
>                    <img src="./public/images/program_icon_02.png" alt="" />
- [ ] Please implement this part too, as the reviewer has a good point

2022-07-26 20:48 UTC, nicupop729 commented on index.html
We know that the designer is not consistent with desktop and mobile, but it was intended.
We always check if the students get this point and that they do the mobile version in one way and the desktop the other for the About page;

- [ ] So please refactor the footer design in order to match the one provided by Behance;

2022-07-26 20:48 UTC, nicupop729 commented on index.html
Regarding the GitHub Flow, the reviewer meant the following:
![image](https://user-images.githubusercontent.com/83596135/181106938-c98b4aa9-088a-458d-8576-3b6e74daa2d2.png)
**Use this link to check the correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).**

At this moment, you are not using GitHub Flow. To use the GitHub Flow, you need to ask to merge your branch in the main when creating the PR.

This aspect is very important and is a reason for the invalidation of the PR. The code reviewer didn't invalidate it but requested it as mandatory.

- [ ] As it is a very important aspect, please try to rename your branches in such a way that you use correctly the GitHub Flow.

2022-07-26 20:48 UTC, nicupop729 commented on index.html
**It is fine if you don't refactor the Feature Speakers section.**
**The next reviewer won't check that**

2022-07-26 20:48 UTC, nicupop729 commented on about.html
> +          <h1>Studeio Development Logo</h1>
- [ ] Please make sure to implement this requirement asked by the previous reviewer. :+1:

2022-07-26 20:48 UTC, nicupop729 commented on about.html
>              <img src="./public/images/event1.jpg" alt="" />
- [ ] Please make sure to implement this requirement asked by the previous reviewer. :+1:

2022-07-26 20:48 UTC, nicupop729 commented on index.html
>          </h1>
- [ ] Please make sure to implement this requirement asked by the previous reviewer. :+1:

2022-07-26 21:01 UTC, gnuion commented on index.html
> **It is fine if you don't refactor the Feature Speakers section.** **The next reviewer won't check that**

What do you mean by refactoring? It already matches the design, but for very small screen sizes I had to change the layout a bit, otherwise, it won't work. You can try it yourself.

2022-07-26 21:02 UTC, gnuion commented on index.html
> We know that the designer is not consistent with desktop and mobile, but it was intended. We always check if the students get this point and that they do the mobile version in one way and the desktop the other for the About page;
> 
> * [ ]  So please refactor the footer design in order to match the one provided by Behance;

By refactoring, I understand breaking code into several files.  However, you do mean it in a different context.

2022-07-26 21:14 UTC, gnuion commented
> Hello @gnuion 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Very nice project you have here! 🎊 Congratulations! 👏
> 
> Please implement the following requests from the previous reviewer:
> 
> * [ ]   Kindly ensure to use the GitHub flow correctly, master or main should be your base branch.
> * [ ]   Kindly ensure the footer section for the about page desktop view has a dark background as it's in the design;
> * [ ]   Kindly ensure to add background images as in the design, currently both your pages don't have background images.
> * [ ]  Kindly ensure to include the top short bar section with social media links, logout, and language links as in the design
> 
> Being in this position, please understand that Microverse tries to replicate as much as possible the workflow from an environment of developers:
> 
> * a designer creates the design;
> * a team of developers creates the app following the design (where they assume that if the design seems to be inconsistent, it was intended; they can always double-check, of course, but in this case, the inconsistencies spotted very well by you, were intended);
> * and there are the team leaders who are reviewing and checking the code;
> 
> As this flow was intended, please try to get the advice from the reviewers as they only want to help
> 
> When ready, please ask for another review in the dashboard!
> 
> Keep rocking 🚀!

I think there should be more talk between product stakeholders. The exclusive culture you are describing doesn't fit me. But I will adapt anyways.

2022-07-26 21:40 UTC, nicupop729 commented on index.html
[OPTIONAL]  -

If you believe it is doable, and if you want to challenge yourself, you can try to respect the Behance design:

BEHANCE design - About page - desktop version:
![image](https://user-images.githubusercontent.com/83596135/181116625-ef2cf188-441d-45cc-bf32-aff03aaf2f2e.png)

Please notice that the partners' section is not here anymore.
Also, please notice that the footer now has a dark background;

BEHANCE design - About page - mobile version:
![image](https://user-images.githubusercontent.com/83596135/181116841-fa940d38-1c91-4e97-a5c0-cb3aed57aee9.png)

Here we have the partners' section back;
The footer is white in this case;

2022-07-26 22:24 UTC, gnuion commented on index.html
Yes, it is doable, although not best practice. One should use consistent design for desktop and mobile. I'd rather work smart than hard. Thank you for taking the time to review my code.

2022-07-27 03:41 UTC, gnuion commented on index.html
Okay, I noticed a problem with the speakers' section. For bigger screen sizes, the text-align should be left.

2022-07-27 04:41 UTC, gnuion commented
I admit I did mess up with the pull request. I should have made just one. But for some reason, I thought it would be good to have more pull requests as this project is a bit more complex. For now, the only solution is to merge the previous pull request without review and take this current pull request for review. I am sorry for this. 😅

2022-07-27 05:32 UTC, gnuion commented on index.html
Another problem that the first reviewer wanted to point out, but I did not understand correctly is that the breakpoint of 768px might be too high for the speakers' section.  So I set it lower for the transition to happen sooner.

2022-07-27 05:45 UTC, gnuion commented on index.html
Okay, I did this part. Make sure you hit the breakpoint!
![image](https://user-images.githubusercontent.com/16549839/181170339-2732b70d-db18-4047-af63-183243e309ec.png)

2022-07-27 06:07 UTC, tufoinnkuo10 requested changes
Hi @gnuion 

Great job so far. you made almost all the requested changes. There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ all sections work correctly
✅design well followed 

Required Changes ♻️
Check the comments under the review
- [ required] like the previous reviewer noted, kindly add a background image to your home and about  main sections so they really follow the Behance design. Great job 👍🏾 


![tufoin](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)



Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-27 06:07 UTC, tufoinnkuo10 commented on about.html
>            <li><a href="#news">News</a></li>
- [ optional] you can set the menu links to take you to the different page section. this will ease navigation

2022-07-27 06:20 UTC, gnuion commented
@tufoinnkuo10 if I understood it correctly, we are allowed to change images.

![image](https://user-images.githubusercontent.com/16549839/181175518-28419a08-4e72-4dcf-8701-47df7263eb93.png)

2022-07-27 08:10 UTC, tufoinnkuo10 commented on about.html
>            <li><a href="#news">News</a></li>
@gnuion i simply asked for the changes requested by the previous reviewer. if thats the case i think you are good to go then

2022-07-27 08:11 UTC, tufoinnkuo10 commented
@gnuion i simply asked for the changes requested by the previous reviewer. if thats the case i think you are good to go then

2022-07-27 08:16 UTC, sinansevgi reviewed
Hello @gnuion  👋,

_This is an additional review as a result of the second opinion request._

I can see that you **have already added** background images to the requested places. Since you expected to customize the website's content in this project, you can use different background images in a similar tone. I think your project should be approved.

As this was the only reason that your project was not approved **it will be approved** as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as **approved** right away :)

Keep rocking 🚀!

2022-07-27 08:30 UTC, gnuion commented
Thank you all for the great feedback! I think my project looks more complete now!

2022-07-27 08:38 UTC, ShoiraTa approved these changes
## **STATUS: APPROVED  🟢 ** 
------
### Hi @gnuion , 

**Great work on making the changes requested by a previous reviewers 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 08:40 UTC, merged